### ISSUE TITLE
TypeError: 'coo_matrix' object is not subscriptable

### ISSUE THREAD

**Issue by NBurnaevskiy** [single-cell-genetics/MQuad#20]
am encountering the same issue that was noticed by another user.

my input is two matrices, AD and DP
mquad -m cellSNP.tag.AD.mtx,cellSNP.tag.DP.mtx -o ./mquad/ --minDP 5 -p 20

output
[MQuad] Loading matrix files ...
16569 variants detected...
Variant names detected...
CPUs used: 20, batch size: 128
Fitting in sparse mode...
Initializing fit(mode: deltaBIC) on 16569 variants...
Traceback (most recent call last):
File "/Users/nikolay/anaconda3/envs/python-3.11.3/bin/mquad", line 8, in
sys.exit(main())
^^^^^^
File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/site-packages/mquad/mquad_CLI.py", line 132, in main
df = mdphd.fit_deltaBIC(
^^^^^^^^^^^^^^^^^^^
File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/site-packages/mquad/mquad_batch_mixbin.py", line 142, in fit_deltaBIC
results = pool.starmap_async(fit_batch, self._batchify(batch_size, x, y, valid_row_sizes)).get()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/multiprocessing/pool.py", line 382, in starmap_async
return self._map_async(func, iterable, starmapstar, chunksize,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/multiprocessing/pool.py", line 478, in _map_async
iterable = list(iterable)
^^^^^^^^^^^^^^
File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/site-packages/mquad/mquad_batch_mixbin.py", line 80, in _batchify
_ad = np.squeeze(np.asarray(self.ad[_x, _y]))
~~~~~~~^^^^^^^^
TypeError: 'coo_matrix' object is not subscriptable

**Comment by aaronkwc** [comment]
Hi @drSnuce,

Can I please have a brief look at the dimensions of the input files? For example something like

`head cellSNP.tag.DP.mtx`

will really help me debug the issue.

Aaron

**Comment by drSnuce** [comment]
Aaron,
I was able to use mquad by using a folder argument instead of passing just two matrices (-c instead of -m). However, it is worth to troubleshoot the issue, since I am second user encountering the problem. Here is the output of head cellSNP.tag.DP.mtx:
%%MatrixMarket matrix coordinate integer general
%
16569	10556	36003472
1	189	1
1	855	1
1	994	2
1	1159	1
1	1278	1
1	1414	1
1	1605	1

Output of head cellSNP.tag.AD.mtx
%%MatrixMarket matrix coordinate integer general
%
16569	10556	304384
11	3595	1
25	10273	1
32	1848	1
32	9473	1
41	2988	1
42	10295	1
53	3735	1.

Both matrices are produced by cellsnp-lite.

Nikolay.

**Comment by aaronkwc** [comment]
Hi Nikolay,

Thanks for reporting the issue and sorry for the late reply. I have made a new release (0.1.7) which should fix this issue. You can update via pip or cloning the newest version of this repo. Let me know if it still persists.

Aaron
