### ISSUE TITLE
Lack of variants identified

### ISSUE THREAD

**Issue by NickolasTeo** [single-cell-genetics/MQuad#22]
[deltaBIC_cdf.pdf](https://github.com/single-cell-genetics/MQuad/files/12354342/deltaBIC_cdf.pdf)
[top variants heatmap.pdf](https://github.com/single-cell-genetics/MQuad/files/12354343/top.variants.heatmap.pdf)
With reference to the two outputs above, in 1 out of 3 of my datasets, I am unable to identify mitochondrial variants. Manually setting the cutoff to 0.9 results in more variants being identified, but there is no diversity among the cells, despite this being a tumour sample where a mutational burden is expected (and does occur in the 2 other samples)

Any advice on can give on this is greatly appreciated. The MQuad inputs were pre-processed with cellSNP lite, using 10X cell ranger's possorted bam and barcodes, with --chrom specific to chrM

**Comment by aaronkwc** [comment]
Hi @NickolasTeo ,

For 10X scRNA-seq data, the sequencing depth is highly variable and also biased to 3' end. Although mutational burden is expected, if the mutation doesn't happen to land in the well covered segments then MQuad has little confidence in calling it due to low depth. I'd recommend checking the depth by plotting out the DP. 

Also, in your top variants heatmap, there seems to be some heterogeneity of the variant among cells?

**Comment by NickolasTeo** [comment]
Dear Aaron,

Thank you for your comments! I sequenced my samples using a 10X 5' kit. Would this impact the analysis pipeline in any way?

Secondly, could you please clarify what you mean by 'checking the depth by plotting out the DP'?
As in what should I do with cellSNP lite's DP matrix to plot it
The file size of the passed_dp and passed_ad is much smaller in this sample compared to the other two, are there settings I should adjust to get more to pass?

Lastly, regarding the last point, attached is the result after changing the cutoff. Each cell either contains all variants at the same intensity, or none at all.
On a tangent, how should I interpret the colour intensity of the heatmap?
[top variants heatmap.pdf](https://github.com/single-cell-genetics/MQuad/files/12406776/top.variants.heatmap.pdf)

Thank you for your help!

**Comment by aaronkwc** [comment]
The 10X 5'kit performs similarly with the 3' kit iirc, with the enrichment being in the reverse direction. This will impact the pipeline similarly as in if the informative mutations don't happen in the enriched 5' ends, MQuad will have a hard time identifying them due to insufficient depth.

One way to check it as I suggested is to use the cellSNP lite DP.mtx. It is a sparse matrix with dimensions n_position x n_cell (assuming you used no filters in the cellSNP procedure you will have ¬16569 positions) containing the depth of each cell in each pos. You can read it into R or python and visualize it by summing over the cells and plotting it against position (a line plot with x axis as position and y axis as total count in each position). I expect to observe highly enriched regions in the 5' end and almost no reads in everywhere else.

The size of the passed_ad and passed_dp is small because there are very few variants to be identified as informative due to shallow sequencing. Unfortunately this is a major limitation of droplet-based sequencing, I don't recommend relaxing the threshold too much just to get more variants because it is likely that most of those have 1 or 2 total DP which is hard to confidently say they are informative, but this is up to your judgement.

The color intensity represents the allele frequency (AD/DP). Deeper means higher AF. You can manually make the same plot by importing AD and DP matrices yourself if you wish to adjust the color scheme.

Hope this helps.
