### ISSUE TITLE
heat map code enquiry 

### ISSUE THREAD

**Issue by sxf-ux** [single-cell-genetics/MQuad#27]
Hi.

I had a question

which section of your scripts made the heat map? my mquad had a bug when I ran it where it did not plot the heat maps in a format which is visible and I dont want to rerun everything again. Id ideally just utilise my outputs to make the heatmap myself 

Thank you !

**Comment by aaronkwc** [comment]
Hi @sxf-ux

The plotting code is wrapped in the `selectInformativeVariants()` function. There was a bug where the plotting style in matplotlib was deprecated, but I have fixed in the latest release so I would recommend updating to 0.1.8. You can then use the `--BICparams` option and use the debug_unsorted_BIC_params.csv to only do the plotting without refitting the model.

If you want to customise the plots yourself, you can do so with the `passed_ad.mtx` and `passed_dp.mtx` for allele frequency heatmaps.

**Comment by aaronkwc** [comment]
Sorry for the confusion. The input should be your original input to MQuad (the full ad dp mtx) instead of the mquad-selected ones. Using the example input file and assuming test is your original output that failed:

`mquad --vcfData example/example.vcf.gz --BICparams example_test/debug_unsorted_BIC_params.csv -o test`
